# Generated by Django 4.1.3 on 2022-12-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('number', models.IntegerField(help_text='질문번호', primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, help_text='질문내용', max_length=100, null=True)),
                ('test_column', models.CharField(blank=True, choices=[('body', '신체'), ('recognition', '인지'), ('language', '언어'), ('emotion', '정서'), ('sociality', '사회성'), ('autism', '자폐경향성'), ('adhd', 'ADHD경향성')], help_text='규준표 컬럼', max_length=11, null=True)),
                ('group', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], help_text='질문그룹', max_length=1, null=True)),
            ],
        ),
    ]
