# Generated by Django 4.1.3 on 2022-12-07 05:54

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_delete_answer'),
        ('growthTest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, help_text='제출답안 리스트', null=True, size=None)),
                ('child', models.OneToOneField(blank=True, help_text='검사 아동', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_child', to='user.child')),
            ],
        ),
    ]
