# Generated by Django 4.1.3 on 2022-12-13 10:30

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_child_tested_at_tester_relationship_and_more'),
        ('growthTest', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[0], help_text='제출답안 리스트', size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='child',
            field=models.OneToOneField(default=1, help_text='검사 아동', on_delete=django.db.models.deletion.CASCADE, related_name='answer_child', to='user.child'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='classification',
            field=models.CharField(default='a', help_text='분류', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(default='a', help_text='코멘트 내용', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='stage',
            field=models.CharField(default='a', help_text='단계', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.CharField(default='a', help_text='질문내용', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='group',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', help_text='질문그룹', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='test_column',
            field=models.CharField(choices=[('body', '신체'), ('recognition', '인지'), ('language', '언어'), ('emotion', '정서'), ('sociality', '사회성'), ('autism', '자폐경향성'), ('adhd', 'ADHD경향성')], default='body', help_text='규준표 컬럼', max_length=11),
            preserve_default=False,
        ),
    ]
