# Generated by Django 4.1.3 on 2022-12-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growthTest', '0006_rename_test_column_question_column_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='column',
            field=models.CharField(choices=[('신체', '신체'), ('인지', '인지'), ('언어', '언어'), ('정서', '정서'), ('사회성', '사회성'), ('자폐경향성', '자폐경향성'), ('ADHD경향성', 'ADHD경향성')], help_text='규준표 컬럼', max_length=7),
        ),
    ]
