# Generated by Django 4.1.3 on 2022-12-06 05:11

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncheonRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('si', models.CharField(blank=True, help_text='시', max_length=10, null=True)),
                ('gu', models.CharField(blank=True, help_text='구/군', max_length=10, null=True)),
                ('emd', models.CharField(blank=True, help_text='읍면동', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='이름', max_length=10, null=True)),
                ('birthDate', models.DateField(blank=True, help_text='생년월일', null=True)),
                ('email', models.EmailField(blank=True, help_text='이메일', max_length=254, null=True)),
                ('privacy_agree', models.BooleanField(default=False, help_text='개인정보수집동의')),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='이름', max_length=10, null=True)),
                ('birthDate', models.DateField(blank=True, help_text='생년월일', null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', '남자'), ('F', '여자')], help_text='성별', max_length=1, null=True)),
                ('kindergarden', models.CharField(blank=True, help_text='유치원 이름', max_length=20, null=True)),
                ('testDate', models.DateField(blank=True, help_text='검사일', null=True)),
                ('residence', models.ForeignKey(blank=True, help_text='거주지역', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residence', to='user.incheonregion')),
                ('tester', models.ForeignKey(blank=True, help_text='검사자', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tester', to='user.tester')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, help_text='제출답안 리스트', null=True, size=None)),
                ('child', models.ForeignKey(blank=True, help_text='검사 아동', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='user.child')),
            ],
        ),
    ]
