# Generated by Django 4.1.3 on 2022-12-06 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='tester',
        ),
        migrations.AddField(
            model_name='tester',
            name='child',
            field=models.OneToOneField(blank=True, help_text='검사 아동', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tester_child', to='user.child'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='child',
            field=models.OneToOneField(blank=True, help_text='검사 아동', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_child', to='user.child'),
        ),
    ]
