# Generated by Django 4.1.3 on 2022-12-06 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_child_tester_tester_child_alter_answer_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='testDate',
        ),
    ]
