# Generated by Django 4.1.3 on 2022-12-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_child_testdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='privacy_agree',
            field=models.BooleanField(default=False, help_text='개인정보수집동의'),
        ),
    ]
