# Generated by Django 4.1.3 on 2022-12-07 02:15

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_child_privacy_agree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tester',
            name='email',
        ),
        migrations.AddField(
            model_name='tester',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='연락처', max_length=128, null=True, region=None),
        ),
    ]
