# Generated by Django 4.1.3 on 2022-12-07 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_tester_email_tester_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
