# Generated by Django 4.1.3 on 2022-12-13 10:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_tester_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='tested_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, help_text='검사일'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tester',
            name='relationship',
            field=models.CharField(choices=[('F', '부'), ('M', '모'), ('G', '조부모'), ('T', '교사'), ('E', '기타')], default='F', help_text='아동과의 관계', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='child',
            name='birthDate',
            field=models.DateField(default=django.utils.timezone.now, help_text='생년월일'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='child',
            name='gender',
            field=models.CharField(choices=[('M', '남자'), ('F', '여자')], default='M', help_text='성별', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='child',
            name='name',
            field=models.CharField(default='a', help_text='이름', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='child',
            name='residence',
            field=models.ForeignKey(default=1, help_text='거주지역', on_delete=django.db.models.deletion.CASCADE, related_name='residence', to='user.incheonregion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incheonregion',
            name='emd',
            field=models.CharField(default='a', help_text='읍면동', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incheonregion',
            name='gu',
            field=models.CharField(default='a', help_text='구/군', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incheonregion',
            name='si',
            field=models.CharField(default='a', help_text='시', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tester',
            name='child',
            field=models.OneToOneField(default=1, help_text='검사 아동', on_delete=django.db.models.deletion.CASCADE, related_name='tester_child', to='user.child'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tester',
            name='name',
            field=models.CharField(default='a', help_text='이름', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tester',
            name='phone_number',
            field=models.CharField(default='01000000000', help_text='연락처', max_length=11),
            preserve_default=False,
        ),
    ]
