# Generated by Django 4.1.3 on 2022-12-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_child_tested_at_tester_relationship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tester',
            name='relationship',
            field=models.CharField(blank=True, choices=[('F', '부'), ('M', '모'), ('G', '조부모'), ('T', '교사'), ('E', '기타')], help_text='아동과의 관계', max_length=1, null=True),
        ),
    ]
