# Generated by Django 4.1.3 on 2022-12-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_tester_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tester',
            name='relationship',
            field=models.CharField(choices=[('F', '부'), ('M', '모'), ('G', '조부모'), ('T', '교사'), ('E', '기타')], default='F', help_text='아동과의 관계', max_length=1),
            preserve_default=False,
        ),
    ]
