# Generated by Django 4.1.3 on 2022-12-27 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='residence',
            field=models.ForeignKey(help_text='거주지역', on_delete=django.db.models.deletion.CASCADE, related_name='residence', to='user.region'),
        ),
        migrations.DeleteModel(
            name='IncheonRegion',
        ),
    ]
