# Generated by Django 4.1.3 on 2022-12-27 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_child_residence_delete_incheonregion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='privacy_agree',
        ),
    ]
