# Generated by Django 4.1.3 on 2022-12-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_remove_child_privacy_agree'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='age',
            field=models.IntegerField(default=1, help_text='만나이'),
            preserve_default=False,
        ),
    ]
